# Workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch or a tag
  push:
    branches:
      - develop
    tags:
      - 'v[0-9]+'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Create release when pushing to develop
  create-release:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      
      - name: Get latest tag
        id: get_latest_tag
        run: |
          git fetch --tags
          echo "latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_OUTPUT
      
      - name: Bump version and push tag
        id: tag_version
        run: |
          latest="${{ steps.get_latest_tag.outputs.latest_tag }}"
          new_tag="v$((${latest#v} + 1))"
          git tag $new_tag
          git push origin $new_tag
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

  # Deploy job
  deploy:
    needs: [create-release]
    if: always() && (github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
